services:
  frontend:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: todo-list
    volumes:
      - .:/app          # mapeia seu código local para dentro do container
      - /app/node_modules
    ports:
      - "5173:5173"     # porta padrão do Vite
    environment:
      - CHOKIDAR_USEPOLLING=true